name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Publish
        uses: BigWigsMods/packager@v2
        with:
          args: -d
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to CurseForge
        uses: BigWigsMods/packager@v2
        with:
          args: -p ${{ secrets.CURSEFORGE_PROJECT_ID }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Upload to WoWInterface
        uses: BigWigsMods/packager@v2
        with:
          args: -w ${{ secrets.WOWINTERFACE_ADDON_ID }}
        env:
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Upload to Wago
        uses: BigWigsMods/packager@v2
        with:
          args: -a ${{ secrets.WAGO_PROJECT_ID }}
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Create GitHub Release
        uses: BigWigsMods/packager@v2
        with:
          args: -z
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
